### ISSUE TITLE
AttributeError: module 'roop.globals' has no attribute 'temp_frame_quality'

### ISSUE THREAD

**Issue by mzeidhassan** [vectorobject/faceswap#2]
Hi @vectorobject 

I am getting this error once I click on "Generate".

`Traceback (most recent call last):
  File "D:\roop-main\server.py", line 150, in do_POST
    evalResult=eval("self.func_"+post_data)
  File "<string>", line 1, in <module>
  File "D:\roop-main\server.py", line 184, in func_swap_video
    extract_frames(target_path,temp_output_dir,fps)
  File "D:\roop-main\server.py", line 20, in extract_frames
    temp_frame_quality = roop.globals.temp_frame_quality * 31 // 100
AttributeError: module 'roop.globals' has no attribute 'temp_frame_quality'
127.0.0.1 - - [08/Aug/2023 20:44:33] "POST / HTTP/1.1" 200 -
[Response] {'code': -2, 'errMsg': "module 'roop.globals' has no attribute 'temp_frame_quality'", 'result': None}
[Request] swap_video([{'file':r'D:\faceswap\faceswap_release_1.0.0\images\sisi.jpg','face':0}],[{'file':r'D:\faceswap\faceswap_release_1.0.0\temp\1691549017511.png','face':1}],r'D:\faceswap\faceswap_release_1.0.0\images\Untitled video (3).mp4',r'D:\faceswap\faceswap_release_1.0.0\output\14555.mp4',False,0.3)`

Any idea?

Thanks

**Comment by mzeidhassan** [comment]
Updating roop to the latest version fixes it and the error doesn't show up any longer.
